package it.akademija.journal;

public enum OperationType {
	SUCCESSFUL_LOGIN,
	UNSUCCESSFUL_LOGIN,
	LOGOUT,
	APPLICATION_SUBMITED,
	APPLICATION_DELETED,
	MEDICAL_RECORD_SUBMITED,
	MEDICAL_RECORD_DOWNLOADED,
	USER_DATA_CHANGED,
	KINDERGARTEN_CREATED,
	KINDERGARTEN_UPDATED,
	KINDERGARTEN_DELETED,
	REGISTRATION_STARTED,
	REGISTRATION_ENDED
}
